apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: nick-app-pipeline-run-
spec:
  params:
    - name: source-repo
      value: git@github.com:cloud-native-garage-method-cohort/nick-morgan-buildah-assignment.git
    - name: image-repo
      value: quay.io/nicholasmorgan/sef-study-express
    - name: app-name
      value: nick-sef-study-express
  pipelineRef:
    name: nodejs-pipeline
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
